!Command
name: IMU_REQ_DATA
opcode: 0x26
subsystem: Attitude
desc: Generic_imu Request Data Packet Command
arguments:
  - !Fixed
    name: CCSDS_STREAMID
    desc: CCSDS Packet Identification
    type: MSB_U16
    value: 0x1926
  - !Fixed
    name: CCSDS_SEQUENCE
    desc: CCSDS Packet Sequence Control
    type: MSB_U16
    value: 0xc000
  - !Fixed
    name: CCSDS_LENGTH
    desc: CCSDS Packet Data Length
    type: MSB_U16
    value: 1
  - !Fixed
    name: CCSDS_FC
    desc: CCSDS Command Function Code
    type: U8
    value: 1
  - !Fixed
    name: CCSDS_CHECKSUM
    desc: CCSDS Command Checksum
    type: U8
    value: 0
