services:
  gsw-ait:
    container_name: gsw-ait
    hostname: ait
    platform: linux/amd64
    build:
      context: .
    environment:
      LOG_LEVEL: INFO
    ports:
      - 8001:8001
    networks:
      - ait
    command: ["source ~/.bashrc && ait-server"]

  nos-fsw:
    container_name: nos-fsw
    hostname: nos_fsw
    platform: linux/amd64
    build:
      context: .
    networks:
      - ait
    command: ["source ~/.bashrc && nc -lvu 0.0.0.0 5012"]

  ttc-command:
    image: ghcr.io/sphinxdefense/ttc-command:main
    platform: linux/amd64
    container_name: ttc-command
    ports:
      - 80:80
    networks:
      - ait

  telem:
    container_name: telem
    platform: linux/amd64
    build:
      context: .
    depends_on: [gsw-ait]
    command: ["source ~/.bashrc && python ./scripts/udp_replay.py"]
    environment:
      HOST: gsw-ait
      PORT: 5013
    networks:
      - ait

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
        INFLUXDB_DB: ait
        INFLUXDB_ADMIN_USER: root
        INFLUXDB_ADMIN_PASSWORD: root
    networks:
      - ait



networks:
  ait:
    name: ait
