services:
  gsw-ait:
    container_name: gsw-ait
    platform: linux/amd64
    build:
      context: .
    environment:
      LOG_LEVEL: INFO
    ports:
      - 8001:8001
    networks:
      - ait
    command: ["source ~/.bashrc && ait-server"]

  gsw-api:
    container_name: gsw-api
    platform: linux/amd64
    build:
      context: .
    environment:
      LOG_LEVEL: INFO
    networks:
      - ait
    ports:
      - 8000:8000
      - 8765:8765
    command: ["source ~/.bashrc && uvicorn api.main:app --host=0.0.0.0 --port=8000 --log-config=logging.yml"]
    #command: ["sleep infinity"]

  telem:
    container_name: telem
    platform: linux/amd64
    build:
      context: .
    depends_on: [gsw-ait]
    command: ["source ~/.bashrc && python ./scripts/udp_replay.py"]
    environment:
      HOST: gsw-ait
      PORT: 5013
    networks:
      - ait

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
        INFLUXDB_DB: ait
        INFLUXDB_ADMIN_USER: root
        INFLUXDB_ADMIN_PASSWORD: root
    networks:
      - ait



networks:
  ait:
    name: ait
