---
version: 1
disable_existing_loggers: false
formatters:
  basic:
    fmt: "%(levelprefix)s %(message)s"
  default:
    "()": "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s %(message)s"
    use_colors:
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  basic:
    formatter: basic
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
  default:
    formatter: default
    class: logging.StreamHandler
    stream: "ext://sys.stderr"
  access:
    formatter: access
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
loggers:
  uvicorn:
    handlers:
      - default
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers:
      - access
    level: INFO
    propagate: false
  api:
    handlers:
      - basic
    level: DEBUG
    propagate: true
