!Packet
name: SAMPLE_DATA_TLM
fields:
- !Field
  name: DEVICE_COUNTER
  desc: Reported Device Command Counter
  type: LSB_U32

- !Field
  name: SAMPLE_X
  desc: Raw sample data x component (1-65535)
  type: LSB_U16
  dntoeu:
      equation: (raw.SAMPLE_X - 32768.0)/32767.0

- !Field
  name: SAMPLE_Y
  desc: Raw sample data y component (1-65535)
  type: LSB_U16
  dntoeu:
      equation: (raw.SAMPLE_Y - 32768.0)/32767.0

- !Field
  name: SAMPLE_Z
  desc: Raw sample data z component (1-65535)
  type: LSB_U16
  dntoeu:
      equation: (raw.SAMPLE_Z - 32768.0)/32767.0
