!Command
name: EPS_SWITCH_CC
opcode: 0x19
subsystem: Electrical
desc: Generic_eps Switch Command
arguments:
  - !Fixed
    name: CCSDS_STREAMID
    desc: CCSDS Packet Identification
    type: MSB_U16
    bytes: [0, 1]
    value: 0x191a
  - !Fixed
    name: CCSDS_SEQUENCE
    desc: CCSDS Packet Sequence Control
    type: MSB_U16
    bytes: [2, 3]
    value: 0xc000
  - !Fixed
    name: CCSDS_LENGTH
    desc: CCSDS Packet Data Length
    type: MSB_U16
    bytes: [4, 5]
    value: 3
  - !Fixed
    name: CCSDS_FC
    desc: CCSDS Command Function Code
    type: U8
    bytes: 6
    value: 2
  - !Fixed
    name: CCSDS_CHECKSUM
    desc: CCSDS Command Checksum
    type: U8
    bytes: 7
    value: 0
  - !Argument
    name:  SWITCH_NUMBER
    desc:  Switch Number (0-7)
    units: none
    type:  U8
    bytes: 8
    enum:
      0x00: SWITCH_0
      0x01: SWITCH_1
      0x02: SWITCH_2
      0x03: SWITCH_3
      0x04: SWITCH_4
      0x05: SWITCH_5
      0x06: SWITCH_6
      0x07: SWITCH_7
      0xFF: UNDEFINED

  - !Argument
    name:  STATE
    desc:   "ON / OFF"
    units: none
    type:  U8
    bytes: 8
    enum:
      0x00: OFF
      0xAA: ON
