!Packet
name: CFE_ES_SHELLPACKET
fields:
- !Field
  name: SHELLOUTPUT_1
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 1
  type: U8

- !Field
  name: SHELLOUTPUT_2
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 2
  type: U8

- !Field
  name: SHELLOUTPUT_3
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 3
  type: U8

- !Field
  name: SHELLOUTPUT_4
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 4
  type: U8

- !Field
  name: SHELLOUTPUT_5
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 5
  type: U8

- !Field
  name: SHELLOUTPUT_6
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 6
  type: U8

- !Field
  name: SHELLOUTPUT_7
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 7
  type: U8

- !Field
  name: SHELLOUTPUT_8
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 8
  type: U8

- !Field
  name: SHELLOUTPUT_9
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 9
  type: U8

- !Field
  name: SHELLOUTPUT_10
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 10
  type: U8

- !Field
  name: SHELLOUTPUT_11
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 11
  type: U8

- !Field
  name: SHELLOUTPUT_12
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 12
  type: U8

- !Field
  name: SHELLOUTPUT_13
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 13
  type: U8

- !Field
  name: SHELLOUTPUT_14
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 14
  type: U8

- !Field
  name: SHELLOUTPUT_15
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 15
  type: U8

- !Field
  name: SHELLOUTPUT_16
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 16
  type: U8

- !Field
  name: SHELLOUTPUT_17
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 17
  type: U8

- !Field
  name: SHELLOUTPUT_18
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 18
  type: U8

- !Field
  name: SHELLOUTPUT_19
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 19
  type: U8

- !Field
  name: SHELLOUTPUT_20
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 20
  type: U8

- !Field
  name: SHELLOUTPUT_21
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 21
  type: U8

- !Field
  name: SHELLOUTPUT_22
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 22
  type: U8

- !Field
  name: SHELLOUTPUT_23
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 23
  type: U8

- !Field
  name: SHELLOUTPUT_24
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 24
  type: U8

- !Field
  name: SHELLOUTPUT_25
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 25
  type: U8

- !Field
  name: SHELLOUTPUT_26
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 26
  type: U8

- !Field
  name: SHELLOUTPUT_27
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 27
  type: U8

- !Field
  name: SHELLOUTPUT_28
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 28
  type: U8

- !Field
  name: SHELLOUTPUT_29
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 29
  type: U8

- !Field
  name: SHELLOUTPUT_30
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 30
  type: U8

- !Field
  name: SHELLOUTPUT_31
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 31
  type: U8

- !Field
  name: SHELLOUTPUT_32
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 32
  type: U8

- !Field
  name: SHELLOUTPUT_33
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 33
  type: U8

- !Field
  name: SHELLOUTPUT_34
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 34
  type: U8

- !Field
  name: SHELLOUTPUT_35
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 35
  type: U8

- !Field
  name: SHELLOUTPUT_36
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 36
  type: U8

- !Field
  name: SHELLOUTPUT_37
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 37
  type: U8

- !Field
  name: SHELLOUTPUT_38
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 38
  type: U8

- !Field
  name: SHELLOUTPUT_39
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 39
  type: U8

- !Field
  name: SHELLOUTPUT_40
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 40
  type: U8

- !Field
  name: SHELLOUTPUT_41
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 41
  type: U8

- !Field
  name: SHELLOUTPUT_42
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 42
  type: U8

- !Field
  name: SHELLOUTPUT_43
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 43
  type: U8

- !Field
  name: SHELLOUTPUT_44
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 44
  type: U8

- !Field
  name: SHELLOUTPUT_45
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 45
  type: U8

- !Field
  name: SHELLOUTPUT_46
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 46
  type: U8

- !Field
  name: SHELLOUTPUT_47
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 47
  type: U8

- !Field
  name: SHELLOUTPUT_48
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 48
  type: U8

- !Field
  name: SHELLOUTPUT_49
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 49
  type: U8

- !Field
  name: SHELLOUTPUT_50
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 50
  type: U8

- !Field
  name: SHELLOUTPUT_51
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 51
  type: U8

- !Field
  name: SHELLOUTPUT_52
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 52
  type: U8

- !Field
  name: SHELLOUTPUT_53
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 53
  type: U8

- !Field
  name: SHELLOUTPUT_54
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 54
  type: U8

- !Field
  name: SHELLOUTPUT_55
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 55
  type: U8

- !Field
  name: SHELLOUTPUT_56
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 56
  type: U8

- !Field
  name: SHELLOUTPUT_57
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 57
  type: U8

- !Field
  name: SHELLOUTPUT_58
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 58
  type: U8

- !Field
  name: SHELLOUTPUT_59
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 59
  type: U8

- !Field
  name: SHELLOUTPUT_60
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 60
  type: U8

- !Field
  name: SHELLOUTPUT_61
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 61
  type: U8

- !Field
  name: SHELLOUTPUT_62
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 62
  type: U8

- !Field
  name: SHELLOUTPUT_63
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 63
  type: U8

- !Field
  name: SHELLOUTPUT_64
  desc: ASCII text string containing output from OS Shell that was received in response
    to an OS Shell Command. byte 64
  type: U8
