!Packet
name: CFE_SB_STATMSG
fields:
- !Field
  name: MSGIDSINUSE
  desc: Current number of MsgIds with a destination.
  type: LSB_U32


- !Field
  name: PEAKMSGIDSINUSE
  desc: Peak number of MsgIds with a destination.
  type: LSB_U32


- !Field
  name: MAXMSGIDSALLOWED
  desc: cFE Cfg Param CFE_SB_MAX_MSG_IDS
  type: LSB_U32


- !Field
  name: PIPESINUSE
  desc: Number of pipes currently in use.
  type: LSB_U32


- !Field
  name: PEAKPIPESINUSE
  desc: Peak number of pipes since last reboot.
  type: LSB_U32


- !Field
  name: MAXPIPESALLOWED
  desc: cFE Cfg Param CFE_SB_MAX_PIPES
  type: LSB_U32


- !Field
  name: MEMINUSE
  desc: Memory bytes currently in use for SB msg transfers.
  type: LSB_U32


- !Field
  name: PEAKMEMINUSE
  desc: Peak memory bytes in use for SB msg transfers.
  type: LSB_U32


- !Field
  name: MAXMEMALLOWED
  desc: cFE Cfg Param CFE_SB_BUF_MEMORY_BYTES
  type: LSB_U32


- !Field
  name: SUBSCRIPTIONSINUSE
  desc: Number of current subscriptions.
  type: LSB_U32


- !Field
  name: PEAKSUBSCRIPTIONSINUSE
  desc: Peak number of subscriptions.
  type: LSB_U32


- !Field
  name: MAXSUBSCRIPTIONSALLOWED
  desc: product of CFE_SB_MAX_MSG_IDS and CFE_SB_MAX_DEST_PER_PKT
  type: LSB_U32


- !Field
  name: SBBUFFERSINUSE
  desc: Number of SB message buffers currently in use.
  type: LSB_U32


- !Field
  name: PEAKSBBUFFERSINUSE
  desc: Max number of SB message buffers in use.
  type: LSB_U32


- !Field
  name: MAXPIPEDEPTHALLOWED
  desc: cFE Cfg Param CFE_SB_MAX_PIPE_DEPTH
  type: LSB_U32


- !Field
  name: PIPEDEPTHSTATS_1
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 1
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_2
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 2
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_3
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 3
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_4
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 4
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_5
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 5
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_6
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 6
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_7
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 7
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_8
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 8
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_9
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 9
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_10
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 10
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_11
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 11
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_12
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 12
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_13
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 13
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_14
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 14
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_15
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 15
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_16
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 16
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_17
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 17
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_18
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 18
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_19
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 19
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_20
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 20
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_21
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 21
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_22
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 22
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_23
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 23
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_24
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 24
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_25
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 25
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_26
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 26
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_27
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 27
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_28
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 28
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_29
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 29
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_30
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 30
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_31
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 31
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_32
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 32
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_33
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 33
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_34
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 34
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_35
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 35
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_36
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 36
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_37
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 37
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_38
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 38
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_39
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 39
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_40
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 40
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_41
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 41
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_42
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 42
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_43
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 43
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_44
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 44
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_45
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 45
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_46
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 46
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_47
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 47
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_48
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 48
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_49
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 49
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_50
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 50
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_51
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 51
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_52
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 52
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_53
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 53
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_54
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 54
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_55
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 55
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_56
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 56
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_57
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 57
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_58
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 58
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_59
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 59
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_60
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 60
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_61
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 61
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_62
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 62
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_63
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 63
  type: LSB_U64


- !Field
  name: PIPEDEPTHSTATS_64
  desc: Pipe Depth Statistics CFE_SB_PipeDepthStats_t. byte 64
  type: LSB_U64
