!Packet
name: CFE_TBL_TBLREGPACKET
fields:
- !Field
  name: SIZE
  desc: Size, in bytes, of Table.
  type: LSB_U32


- !Field
  name: CRC
  desc: Most recently calculated CRC of Table.
  type: LSB_U32


- !Field
  name: ACTIVEBUFFERADDR
  desc: Address of Active Buffer.
  type: LSB_U32


- !Field
  name: INACTIVEBUFFERADDR
  desc: Address of Inactive Buffer.
  type: LSB_U32


- !Field
  name: VALIDATIONFUNCPTR
  desc: Ptr to Owner App's function that validates tbl contents.
  type: LSB_U32


- !Field
  name: TIMEOFLASTUPDATE_SECONDS
  desc: 'Number of seconds since epoch. (Parent: Time when Table was last updated.)'
  type: LSB_U32


- !Field
  name: TIMEOFLASTUPDATE_SUBSECONDS
  desc: 'Number of subseconds since epoch (LSB = 2^(-32) seconds). (Parent: Time when
    Table was last updated.)'
  type: LSB_U32


- !Field
  name: FILECREATETIMESECS
  desc: File creation time from last file loaded into table.
  type: LSB_U32


- !Field
  name: FILECREATETIMESUBSECS
  desc: File creation time from last file loaded into table.
  type: LSB_U32


- !Field
  name: TABLELOADEDONCE
  desc: Flag indicating whether table has been loaded once or not.
  type: U8


- !Field
  name: LOADPENDING
  desc: Flag indicating an inactive buffer is ready to be copied.
  type: U8


- !Field
  name: DUMPONLY
  desc: Flag indicating Table is NOT to be loaded.
  type: U8


- !Field
  name: DBLBUFFERED
  desc: Flag indicating Table has a dedicated inactive buffer.
  type: U8


- !Field
  name: NAME
  desc: Processor specific table name.
  type: U8

  bytes:
  - 40
  - 343
- !Field
  name: LASTFILELOADED
  desc: Filename of last file loaded into table.
  type: U8

  bytes:
  - 344
  - 855
- !Field
  name: OWNERAPPNAME
  desc: Name of owning application.
  type: U8

  bytes:
  - 856
  - 1015
- !Field
  name: CRITICAL
  desc: Indicates whether table is Critical or not.
  type: U8


- !Field
  name: PADDING
  desc: Spare byte to maintain byte alignment.
  type: U8
