!Packet
name: CFS_MD_HKTLM
fields:
- !Field
  name: INVALIDCMDCNTR
  desc: Count of invalid commands received.
  type: U8


- !Field
  name: VALIDCMDCNTR
  desc: Count of valid commands received.
  type: U8


- !Field
  name: DWELLENABLEDMASK
  desc: Each bit in bit mask enables a table 0x0001=TBL1 enable bit,0x0002=TBL2 enable
    bit, 0x0004=TBL3 enable bit,0x0008=TBL4 enable bit, etc.
  type: LSB_U16


- !Field
  name: DWELLTBLADDRCOUNT_1
  desc: Number of dwell addresses in table. byte 1
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_2
  desc: Number of dwell addresses in table. byte 2
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_3
  desc: Number of dwell addresses in table. byte 3
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_4
  desc: Number of dwell addresses in table. byte 4
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_5
  desc: Number of dwell addresses in table. byte 5
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_6
  desc: Number of dwell addresses in table. byte 6
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_7
  desc: Number of dwell addresses in table. byte 7
  type: U8


- !Field
  name: DWELLTBLADDRCOUNT_8
  desc: Number of dwell addresses in table. byte 8
  type: U8


- !Field
  name: NUMWAITSPERPKT_1
  desc: Number of delay counts in table. byte 1
  type: LSB_U16


- !Field
  name: NUMWAITSPERPKT_2
  desc: Number of delay counts in table. byte 2
  type: LSB_U16


- !Field
  name: NUMWAITSPERPKT_3
  desc: Number of delay counts in table. byte 3
  type: LSB_U16


- !Field
  name: NUMWAITSPERPKT_4
  desc: Number of delay counts in table. byte 4
  type: LSB_U16


- !Field
  name: BYTECOUNT_1
  desc: Number of bytes of data specified by table. byte 1
  type: LSB_U16


- !Field
  name: BYTECOUNT_2
  desc: Number of bytes of data specified by table. byte 2
  type: LSB_U16


- !Field
  name: BYTECOUNT_3
  desc: Number of bytes of data specified by table. byte 3
  type: LSB_U16


- !Field
  name: BYTECOUNT_4
  desc: Number of bytes of data specified by table. byte 4
  type: LSB_U16


- !Field
  name: DWELLPKTOFFSET_1
  desc: Current write offset within dwell pkt data region. byte 1
  type: LSB_U16


- !Field
  name: DWELLPKTOFFSET_2
  desc: Current write offset within dwell pkt data region. byte 2
  type: LSB_U16


- !Field
  name: DWELLPKTOFFSET_3
  desc: Current write offset within dwell pkt data region. byte 3
  type: LSB_U16


- !Field
  name: DWELLPKTOFFSET_4
  desc: Current write offset within dwell pkt data region. byte 4
  type: LSB_U16


- !Field
  name: DWELLTBLENTRY_1
  desc: Next dwell table entry to be processed. byte 1
  type: LSB_U16


- !Field
  name: DWELLTBLENTRY_2
  desc: Next dwell table entry to be processed. byte 2
  type: LSB_U16


- !Field
  name: DWELLTBLENTRY_3
  desc: Next dwell table entry to be processed. byte 3
  type: LSB_U16


- !Field
  name: DWELLTBLENTRY_4
  desc: Next dwell table entry to be processed. byte 4
  type: LSB_U16


- !Field
  name: COUNTDOWN_1
  desc: Current value of countdown timer. byte 1
  type: LSB_U16


- !Field
  name: COUNTDOWN_2
  desc: Current value of countdown timer. byte 2
  type: LSB_U16


- !Field
  name: COUNTDOWN_3
  desc: Current value of countdown timer. byte 3
  type: LSB_U16


- !Field
  name: COUNTDOWN_4
  desc: Current value of countdown timer. byte 4
  type: LSB_U16
