!Packet
name: CFS_CFE_ES_POOLSTATSTLM
fields:
- !Field
  name: POOLHANDLE
  desc: Handle of memory pool whose stats are being telemetered.
  type: LSB_U32

- !Field
  name: POOLSTATS_POOLSIZE
  desc: 'Size of Memory Pool (in bytes). (Parent: For more info, see CFE_ES_MemPoolStats_t.)'
  type: LSB_U32

- !Field
  name: POOLSTATS_NUMBLOCKSREQUESTED
  desc: 'Number of times a memory block has been allocated. (Parent: For more info,
    see CFE_ES_MemPoolStats_t.)'
  type: LSB_U32

- !Field
  name: POOLSTATS_CHECKERRCTR
  desc: 'Number of errors detected when freeing a memory block. (Parent: For more
    info, see CFE_ES_MemPoolStats_t.)'
  type: LSB_U32

- !Field
  name: POOLSTATS_NUMFREEBYTES
  desc: 'Number of bytes never allocated to a block. (Parent: For more info, see CFE_ES_MemPoolStats_t.)'
  type: LSB_U32

- !Field
  name: BLOCKSTATS_1_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_1_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_1_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_2_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_2_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_2_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_3_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_3_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_3_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_4_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_4_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_4_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_5_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_5_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_5_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_6_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_6_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_6_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_7_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_7_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_7_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_8_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_8_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_8_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_9_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_9_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_9_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_10_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_10_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_10_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_11_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_11_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_11_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_12_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_12_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_12_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_13_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_13_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_13_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_14_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_14_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_14_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_15_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_15_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_15_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_16_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_16_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_16_NUM_FREE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_17_SIZE
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_17_NUM_CREATED
  desc: ''
  type: LSB_U32

- !Field
  name: BLOCKSTATS_17_NUM_FREE
  desc: ''
  type: LSB_U32
