!Packet
name: CFS_DS_HKPACKET
fields:
- !Field
  name: CMDACCEPTEDCOUNTER
  desc: Count of valid commands received.
  type: U8

- !Field
  name: CMDREJECTEDCOUNTER
  desc: Count of invalid commands received.
  type: U8

- !Field
  name: DESTTBLLOADCOUNTER
  desc: Count of destination file table loads.
  type: U8

- !Field
  name: DESTTBLERRCOUNTER
  desc: Count of failed attempts to get table data pointer.
  type: U8

- !Field
  name: FILTERTBLLOADCOUNTER
  desc: Count of packet filter table loads.
  type: U8

- !Field
  name: FILTERTBLERRCOUNTER
  desc: Count of failed attempts to get table data pointer.
  type: U8

- !Field
  name: APPENABLESTATE
  desc: Application enable/disable state.
  type: U8

- !Field
  name: SPARE8
  desc: Structure alignment padding.
  type: U8

- !Field
  name: FILEWRITECOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEWRITEERRCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEUPDATECOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEUPDATEERRCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: DISABLEDPKTCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: IGNOREDPKTCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILTEREDPKTCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: PASSEDPKTCOUNTER
  desc: LITTLE_ENDIAN
  type: LSB_U32
