!Packet
name: CFS_CFE_TBL_HKPACKET
fields:
- !Field
  name: CMDCOUNTER
  desc: Count of valid commands received.
  type: U8


- !Field
  name: ERRCOUNTER
  desc: Count of invalid commands received.
  type: U8


- !Field
  name: NUMTABLES
  desc: Number of Tables Registered.
  type: LSB_U16


- !Field
  name: NUMLOADPENDING
  desc: Number of Tables pending on Applications for their update.
  type: LSB_U16


- !Field
  name: VALIDATIONCTR
  desc: Number of completed table validations.
  type: LSB_U16


- !Field
  name: LASTVALCRC
  desc: Data Integrity Value computed for last table validated.
  type: LSB_U32


- !Field
  name: LASTVALSTATUS
  desc: Returned status from validation function for last table validated.
  type: LSB_I32


- !Field
  name: ACTIVEBUFFER
  desc: Indicator of whether table buffer validated was 0=Inactive, 1=Active.
  type: U8


- !Field
  name: LASTVALTABLENAME
  desc: Name of last table validated.
  type: U8

  bytes: [17, 336]
- !Field
  name: SUCCESSVALCTR
  desc: Total number of successful table validations.
  type: U8


- !Field
  name: FAILEDVALCTR
  desc: Total number of unsuccessful table validations.
  type: U8


- !Field
  name: NUMVALREQUESTS
  desc: Number of times Table Services has requested validations from Apps.
  type: U8


- !Field
  name: NUMFREESHAREDBUFS
  desc: Number of free Shared Working Buffers.
  type: U8


- !Field
  name: BYTEALIGNPAD1
  desc: Spare byte to ensure longword alignment.
  type: U8


- !Field
  name: MEMPOOLHANDLE
  desc: Handle to TBL's memory pool.
  type: LSB_U32


- !Field
  name: LASTUPDATETIME_SECONDS
  desc: 'Number of seconds since epoch. (Parent: Time of last table update.)'
  type: LSB_U32


- !Field
  name: LASTUPDATETIME_SUBSECONDS
  desc: 'Number of subseconds since epoch (LSB = 2^(-32) seconds). (Parent: Time of
    last table update.)'
  type: LSB_U32


- !Field
  name: LASTUPDATEDTBL
  desc: Name of the last table updated.
  type: U8

  bytes: [354, 673]
- !Field
  name: LASTFILELOADED
  desc: Path and Name of last table image file loaded.
  type: U8

  bytes: [674, 1185]
- !Field
  name: LASTFILEDUMPED
  desc: Path and Name of last file dumped to.
  type: U8

  bytes: [1186, 1697]
- !Field
  name: LASTTABLELOADED
  desc: Name of the last table loaded.
  type: U8

  bytes: [1698, 2017]
- !Field
  name: PADDING
  desc: Spare bytes to maintain byte alignment.
  type: LSB_U16
