!Packet
name: CFS_CFE_SB_PREVSUBMSG
fields:
- !Field
  name: PKTSEGMENT
  desc: Pkt number(starts at 1) in the series.
  type: LSB_U32


- !Field
  name: TOTALSEGMENTS
  desc: Total number of pkts needed to complete the request.
  type: LSB_U32


- !Field
  name: ENTRIES
  desc: Number of entries in the pkt.
  type: LSB_U32


- !Field
  name: MSGID1
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY1
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY1
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID1
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID2
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY2
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY2
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID2
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID3
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY3
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY3
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID3
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID4
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY4
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY4
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID4
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID5
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY5
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY5
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID5
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID6
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY6
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY6
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID6
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID7
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY7
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY7
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID7
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID8
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY8
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY8
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID8
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID9
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY9
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY9
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID9
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID10
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY10
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY10
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID10
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID11
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY11
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY11
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID11
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID12
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY12
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY12
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID12
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID13
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY13
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY13
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID13
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID14
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY14
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY14
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID14
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID15
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY15
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY15
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID15
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID16
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY16
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY16
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID16
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID17
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY17
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY17
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID17
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID18
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY18
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY18
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID18
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID19
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY19
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY19
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID19
  desc: PipeId portion of the subscription.
  type: U8


- !Field
  name: MSGID20
  desc: MsgId portion of the subscription.
  type: LSB_U16


- !Field
  name: PRIORITY20
  desc: Specify high(1) or low(0) message priority for off-board routing, currently
    unused.
  type: U8


- !Field
  name: RELIABILITY20
  desc: Specify high(1) or low(0) message transfer reliability for off-board routing,
    currently unused.
  type: U8


- !Field
  name: PIPEID20
  desc: PipeId portion of the subscription.
  type: U8
