!Packet
name: DS_FILEINFOPKT
fields:
- !Field
  name: FILEAGE0
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE0
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE0
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT0
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE0
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE0
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE1
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE1
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE1
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT1
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE1
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE1
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE2
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE2
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE2
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT2
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE2
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE2
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE3
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE3
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE3
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT3
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE3
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE3
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE4
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE4
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE4
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT4
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE4
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE4
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE5
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE5
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE5
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT5
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE5
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE5
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE6
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE6
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE6
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT6
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE6
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE6
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE7
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE7
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE7
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT7
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE7
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE7
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE8
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE8
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE8
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT8
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE8
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE8
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE9
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE9
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE9
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT9
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE9
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE9
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE10
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE10
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE10
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT10
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE10
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE10
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE11
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE11
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE11
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT11
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE11
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE11
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE12
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE12
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE12
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT12
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE12
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE12
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE13
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE13
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE13
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT13
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE13
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE13
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE14
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE14
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE14
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT14
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE14
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE14
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: FILEAGE15
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILESIZE15
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: FILERATE15
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: SEQUENCECNT15
  desc: LITTLE_ENDIAN
  type: LSB_U32

- !Field
  name: ENABLESTATE15
  desc: LITTLE_ENDIAN
  type: LSB_U16

- !Field
  name: OPENSTATE15
  desc: LITTLE_ENDIAN
  type: LSB_U16
