!Packet
name: FM_HOUSEKEEPINGPKT
fields:
- !Field
  name: COMMANDCOUNTER
  desc: Application command counter.
  type: U8


- !Field
  name: COMMANDERRCOUNTER
  desc: Application command error counter.
  type: U8


- !Field
  name: SPARE
  desc: Placeholder for unused command warning counter.
  type: U8


- !Field
  name: NUMOPENFILES
  desc: Number of open files in the system.
  type: U8


- !Field
  name: CHILDCMDCOUNTER
  desc: Child task command counter.
  type: U8


- !Field
  name: CHILDCMDERRCOUNTER
  desc: Child task command error counter.
  type: U8


- !Field
  name: CHILDCMDWARNCOUNTER
  desc: Child task command warning counter.
  type: U8


- !Field
  name: CHILDQUEUECOUNT
  desc: Number of pending commands in queue.
  type: U8


- !Field
  name: CHILDCURRENTCC
  desc: Command code currently executing.
  type: U8


- !Field
  name: CHILDPREVIOUSCC
  desc: Command code previously executed.
  type: U8
