!Packet
name: MM_HKPACKET
fields:
- !Field
  name: CMDCOUNTER
  desc: MM Application Command Counter.
  type: U8


- !Field
  name: ERRCOUNTER
  desc: MM Application Command Error Counter.
  type: U8


- !Field
  name: LASTACTION
  desc: Last command action executed.
  type: U8


- !Field
  name: MEMTYPE
  desc: Memory type for last command.
  type: U8


- !Field
  name: ADDRESS
  desc: Fully resolved address used for last command.
  type: LSB_U32


- !Field
  name: DATAVALUE
  desc: Last command data value -- may be fill pattern or peek/poke value.
  type: LSB_U32


- !Field
  name: BYTESPROCESSED
  desc: Bytes processed for last command.
  type: LSB_U32


- !Field
  name: FILENAME
  desc: Name of the data file used for last command, where applicable.
  type: U8

  bytes: [16, 527]
