!Packet
name: SCH_HKPACKET
fields:
- !Field
  name: CMDCOUNTER
  desc: Command Counter.
  type: U8


- !Field
  name: ERRCOUNTER
  desc: Command Error Counter.
  type: U8


- !Field
  name: SYNCTOMET
  desc: Status indicating whether slots are synched to MET.
  type: U8


- !Field
  name: MAJORFRAMESOURCE
  desc: Major Frame Signal source identifier.
  type: U8


- !Field
  name: SCHEDULEACTIVITYSUCCESSCOUNT
  desc: Number of successfully performed activities.
  type: LSB_U32


- !Field
  name: SCHEDULEACTIVITYFAILURECOUNT
  desc: Number of unsuccessful activities attempted.
  type: LSB_U32


- !Field
  name: SLOTSPROCESSEDCOUNT
  desc: 'Total # of Schedule Slots (Minor Frames) Processed.'
  type: LSB_U32


- !Field
  name: SKIPPEDSLOTSCOUNT
  desc: Number of times that slots were skipped.
  type: LSB_U16


- !Field
  name: MULTIPLESLOTSCOUNT
  desc: Number of times that multiple slots processed.
  type: LSB_U16


- !Field
  name: SAMESLOTCOUNT
  desc: '# of times SCH woke up in the same slot as last time'
  type: LSB_U16


- !Field
  name: BADTABLEDATACOUNT
  desc: '# of times corrupted table entries were processed'
  type: LSB_U16


- !Field
  name: TABLEVERIFYSUCCESSCOUNT
  desc: '# of times table loads successfully verified'
  type: LSB_U16


- !Field
  name: TABLEVERIFYFAILURECOUNT
  desc: '# of times table loads unsuccessfully verified'
  type: LSB_U16


- !Field
  name: TABLEPASSCOUNT
  desc: '# of times Schedule Table has been processed'
  type: LSB_U32


- !Field
  name: VALIDMAJORFRAMECOUNT
  desc: '# of valid Major Frame tones received'
  type: LSB_U32


- !Field
  name: MISSEDMAJORFRAMECOUNT
  desc: '# of missing Major Frame tones'
  type: LSB_U32


- !Field
  name: UNEXPECTEDMAJORFRAMECOUNT
  desc: '# of unexpected Major Frame tones'
  type: LSB_U32


- !Field
  name: MINORFRAMESSINCETONE
  desc: '# of Minor Frames since last Major Frame tone'
  type: LSB_U16


- !Field
  name: NEXTSLOTNUMBER
  desc: Next Minor Frame to be processed.
  type: LSB_U16


- !Field
  name: LASTSYNCMETSLOT
  desc: Slot number where Time Sync last occurred.
  type: LSB_U16


- !Field
  name: IGNOREMAJORFRAME
  desc: Major Frame too noisy to trust.
  type: U8


- !Field
  name: UNEXPECTEDMAJORFRAME
  desc: Most Recent Major Frame signal was unexpected.
  type: U8
