!Packet
name: MAG_DATA_TLM
fields:
- !Field
  name: RAW_MAG_X
  desc: Raw mag data x component (nT)
  type: LSB_U32

- !Field
  name: RAW_MAG_Y
  desc: Raw mag data y component (nT)
  type: LSB_U32

- !Field
  name: RAW_MAG_Z
  desc: Raw mag data z component (nT)
  type: LSB_U32
