!Packet
name: ADCS_AC
fields:
- !Field
  name: B_RANGE
  desc: Bdot Magnetic Field Range to Operate In (T)
  type: LSB_D64

- !Field
  name: KB
  desc: Bdot Gain parameter
  type: LSB_D64

- !Field
  name: BOLD_X
  desc: Bdot Old Magnetic Field Vector in Body Frame, X component (T)
  type: LSB_D64

- !Field
  name: BOLD_Y
  desc: Bdot Old Magnetic Field Vector in Body Frame, Y component (T)
  type: LSB_D64

- !Field
  name: BOLD_Z
  desc: Bdot Old Magnetic Field Vector in Body Frame, Z component (T)
  type: LSB_D64

- !Field
  name: BDOT_X
  desc: Bdot Derivative of Magnetic Field Vector in Body Frame, X component (T/s)
  type: LSB_D64

- !Field
  name: BDOT_Y
  desc: Bdot Derivative of Magnetic Field Vector in Body Frame, Y component (T/s)
  type: LSB_D64

- !Field
  name: BDOT_Z
  desc: Bdot Derivative of Magnetic Field Vector in Body Frame, Z component (T/s)
  type: LSB_D64

- !Field
  name: KP_X
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: KP_Y
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: KP_Z
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: KR_X
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: KR_Y
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: KR_Z
  desc: Sunsafe Gain Parameter
  type: LSB_D64

- !Field
  name: SSIDE_X
  desc: Sunsafe sunside vector, X component
  type: LSB_D64

- !Field
  name: SSIDE_Y
  desc: Sunsafe sunside vector, Y component
  type: LSB_D64

- !Field
  name: SSIDE_Z
  desc: Sunsafe sunside vector, Z component
  type: LSB_D64

- !Field
  name: VMAX
  desc: Sunsafe Rate limit (m/s)
  type: LSB_D64

- !Field
  name: CMD_WBN_X
  desc: Sunsafe commanded angular rate, X component
  type: LSB_D64

- !Field
  name: CMD_WBN_Y
  desc: Sunsafe commanded angular rate, Y component
  type: LSB_D64

- !Field
  name: CMD_WBN_Z
  desc: Sunsafe commanded angular rate, Z component
  type: LSB_D64

- !Field
  name: H_MGMT
  desc: Sunsafe allow momentum management
  type: U8

- !Field
  name: THERR_X
  desc: Sunsafe Theta error, X component
  type: LSB_D64

- !Field
  name: THERR_Y
  desc: Sunsafe Theta error, Y component
  type: LSB_D64

- !Field
  name: THERR_Z
  desc: Sunsafe Theta error, z component
  type: LSB_D64

- !Field
  name: WERR_X
  desc: Sunsafe Omega error, X component
  type: LSB_D64

- !Field
  name: WERR_Y
  desc: Sunsafe Omega error, Y component
  type: LSB_D64

- !Field
  name: WERR_Z
  desc: Sunsafe Omega error, Z component
  type: LSB_D64

- !Field
  name: TCMD_X
  desc: Sunsafe torque command, X component
  type: LSB_D64

- !Field
  name: TCMD_Y
  desc: Sunsafe torque command, Y component
  type: LSB_D64

- !Field
  name: TCMD_Z
  desc: Sunsafe torque command, Z component
  type: LSB_D64

- !Field
  name: ERR_T
  desc: Sunsafe error
  type: LSB_D64
