!Packet
name: ADCS_GNC
fields:
- !Field
  name: DT
  desc: Delta T
  type: LSB_D64

- !Field
  name: MAX_MCMD
  desc: Maximum Magnetic Torquer Command (A-m^2)
  type: LSB_D64

- !Field
  name: MODE
  desc: GN&C Mode
  type: U8
  enum:
    0: PASSIVE
    1: BDOT
    2: SUNSAFE
- !Field
  name: H_MGMTON
  desc: Momentum Management off (0) / on (1)
  type: U8
  enum:
    0: 'OFF'
    1: 'ON'
- !Field
  name: MM_KB
  desc: Momentum Management Kb gain
  type: LSB_D64

- !Field
  name: MM_B_RANGE
  desc: Momentum Management magnetic field range
  type: LSB_D64

- !Field
  name: MM_LO_FRAC
  desc: Momentum Management lower limit to disable MM
  type: LSB_D64

- !Field
  name: MM_HI_FRAC
  desc: Momentum Management upper limit to enable MM
  type: LSB_D64

- !Field
  name: MM_ACTIVE_X
  desc: Momentum Management active in X axis
  type: U8

- !Field
  name: MM_ACTIVE_Y
  desc: Momentum Management active in Y axis
  type: U8

- !Field
  name: MM_ACTIVE_Z
  desc: Momentum Management active in Z axis
  type: U8

- !Field
  name: MM_MCMD_X
  desc: Momentum Management magnetorquer command in body frame, X component (A-m^2)
  type: LSB_D64

- !Field
  name: MM_MCMD_Y
  desc: Momentum Management magnetorquer command in body frame, Y component (A-m^2)
  type: LSB_D64

- !Field
  name: MM_MCMD_Z
  desc: Momentum Management magnetorquer command in body frame, Z component (A-m^2)
  type: LSB_D64

- !Field
  name: BVB_X
  desc: Magnetic Field Vector in Body Frame, X component (T)
  type: LSB_D64

- !Field
  name: BVB_Y
  desc: Magnetic Field Vector in Body Frame, Y component (T)
  type: LSB_D64

- !Field
  name: BVB_Z
  desc: Magnetic Field Vector in Body Frame, Z component (T)
  type: LSB_D64

- !Field
  name: SVB_X
  desc: Sun Unit Vector in Body Frame, X component
  type: LSB_D64

- !Field
  name: SVB_Y
  desc: Sun Unit Vector in Body Frame, Y component
  type: LSB_D64

- !Field
  name: SVB_Z
  desc: Sun Unit Vector in Body Frame, Z component
  type: LSB_D64

- !Field
  name: SUN_VALID
  desc: Sun Valid(1) / Invalid(0)
  type: U8

- !Field
  name: WBN_X
  desc: Angular Rate Vector in Body Frame, X component
  type: LSB_D64

- !Field
  name: WBN_Y
  desc: Angular Rate Vector in Body Frame, Y component
  type: LSB_D64

- !Field
  name: WBN_Z
  desc: Angular Rate Vector in Body Frame, Z component
  type: LSB_D64

- !Field
  name: RW_MAX_MOM_X
  desc: Reaction wheel maximum momentum in body frame, X component
  type: LSB_D64

- !Field
  name: RW_MAX_MOM_Y
  desc: Reaction wheel maximum momentum in body frame, Y component
  type: LSB_D64

- !Field
  name: RW_MAX_MOM_Z
  desc: Reaction wheel maximum momentum in body frame, Z component
  type: LSB_D64

- !Field
  name: RW_MOMENTUM_X
  desc: Reaction wheel momentum in body frame, X component
  type: LSB_D64

- !Field
  name: RW_MOMENTUM_Y
  desc: Reaction wheel momentum in body frame, Y component
  type: LSB_D64

- !Field
  name: RW_MOMENTUM_Z
  desc: Reaction wheel momentum in body frame, Z component
  type: LSB_D64

- !Field
  name: MCMD_X
  desc: Magnetorquer Command in Body Frame, X component (A-m^2)
  type: LSB_D64

- !Field
  name: MCMD_Y
  desc: Magnetorquer Command in Body Frame, Y component (A-m^2)
  type: LSB_D64

- !Field
  name: MCMD_Z
  desc: Magnetorquer Command in Body Frame, Z component (A-m^2)
  type: LSB_D64

- !Field
  name: TCMD_X
  desc: Reaction Wheel Torque Command in Body Frame, X component (N-m)
  type: LSB_D64

- !Field
  name: TCMD_Y
  desc: Reaction Wheel Torque Command in Body Frame, Y component (N-m)
  type: LSB_D64

- !Field
  name: TCMD_Z
  desc: Reaction Wheel Torque Command in Body Frame, Z component (N-m)
  type: LSB_D64
