!Packet
name: GENERIC_ADCS_AD
fields:
- !Field
  name: BVB_X
  desc: Magnetic Field Vector in Body Frame, X component (T)
  type: LSB_D64

- !Field
  name: BVB_Y
  desc: Magnetic Field Vector in Body Frame, Y component (T)
  type: LSB_D64

- !Field
  name: BVB_Z
  desc: Magnetic Field Vector in Body Frame, Z component (T)
  type: LSB_D64

- !Field
  name: SUN_VALID
  desc: Sun Unit Vector Valid(1) / Invalid(0)
  type: U8

- !Field
  name: FSS_VALID
  desc: FSS Sun Unit Vector Valid(1) / Invalid(0)
  type: U8

- !Field
  name: SVB_X
  desc: Sun Unit Vector in Body Frame, X component
  type: LSB_D64

- !Field
  name: SVB_Y
  desc: Sun Unit Vector in Body Frame, Y component
  type: LSB_D64

- !Field
  name: SVB_Z
  desc: Sun Unit Vector in Body Frame, Z component
  type: LSB_D64

- !Field
  name: IMU_INIT
  desc: IMU AD initialized
  type: U8

- !Field
  name: ALPHA
  desc: Filter coefficient for IMU wbn data
  type: LSB_D64

- !Field
  name: IMU_VALID
  desc: IMU data valid(1) / invalid(0)
  type: U8

- !Field
  name: WBN_PREV_X
  desc: Previous angular rate, X component
  type: LSB_D64

- !Field
  name: WBN_PREV_Y
  desc: Previous angular rate, Y component
  type: LSB_D64

- !Field
  name: WBN_PREV_Z
  desc: Previous angular rate, Z component
  type: LSB_D64

- !Field
  name: WBN_X
  desc: Angular rate, X component
  type: LSB_D64

- !Field
  name: WBN_Y
  desc: Angular rate, Y component
  type: LSB_D64

- !Field
  name: WBN_Z
  desc: Angular rate, Z component
  type: LSB_D64

- !Field
  name: ACC_X
  desc: Acceleration, X component
  type: LSB_D64

- !Field
  name: ACC_Y
  desc: Acceleration, Y component
  type: LSB_D64

- !Field
  name: ACC_Z
  desc: Acceleration, Z component
  type: LSB_D64
