# - !Command
#   name:      TO_DEBUG_ENABLE_OUTPUT_CC
#   opcode:    0x06
#   ccsds:     { apid: 0x80 }
#   subsystem: TO
#   title:     Enable Telemetry
#   desc:      |
#     Enable Output Command
#   arguments:
#     - !Argument
#       name:  dest_ip
#       desc:  Destination IP
#       units: none
#       type:  S16
#       bytes: [0, 15]
#     - !Argument
#       name:  dest_port
#       desc:  Destination Port
#       units: none
#       type:  MSB_U16
#       bytes: [16, 17]


- !include ./cmd/adcs/ADCS_NOOP_CC.yaml
- !include ./cmd/adcs/ADCS_RST_COUNTERS_CC.yaml
- !include ./cmd/adcs/ADCS_SET_MOMENTUM_MANAGEMENT_CC.yaml
- !include ./cmd/adcs/ADCS_SET_MODE_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_DI_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_AD_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_GNC_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_AC_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_DO_CC.yaml
- !include ./cmd/adcs/ADCS_REQ_HK.yaml
- !include ./cmd/adcs/ADCS_PERFORM_ADAC.yaml
- !include ./cmd/arducam/CAM_EXP3_CC.yaml
- !include ./cmd/arducam/CAM_HW_CHECK_CC.yaml
- !include ./cmd/arducam/CAM_NOOP_CC.yaml
- !include ./cmd/arducam/CAM_RESET_COUNTERS_CC.yaml
- !include ./cmd/arducam/CAM_SEND_HK_CC.yaml
- !include ./cmd/eps/EPS_NOOP_CC.yaml
- !include ./cmd/eps/EPS_REQ_HK.yaml
- !include ./cmd/eps/EPS_RST_COUNTERS_CC.yaml
- !include ./cmd/eps/EPS_SWITCH_CC.yaml
- !include ./cmd/fss/FSS_DISABLE_CC.yaml
- !include ./cmd/fss/FSS_ENABLE_CC.yaml
- !include ./cmd/fss/FSS_NOOP_CC.yaml
- !include ./cmd/fss/FSS_REQ_DATA.yaml
- !include ./cmd/fss/FSS_REQ_HK.yaml
- !include ./cmd/fss/FSS_RST_COUNTERS_CC.yaml
- !include ./cmd/imu/IMU_DISABLE_CC.yaml
- !include ./cmd/imu/IMU_ENABLE_CC.yaml
- !include ./cmd/imu/IMU_NOOP_CC.yaml
- !include ./cmd/imu/IMU_REQ_DATA.yaml
- !include ./cmd/imu/IMU_REQ_HK.yaml
- !include ./cmd/imu/IMU_RST_COUNTERS_CC.yaml
- !include ./cmd/mag/MAG_DISABLE_CC.yaml
- !include ./cmd/mag/MAG_ENABLE_CC.yaml
- !include ./cmd/mag/MAG_NOOP_CC.yaml
- !include ./cmd/mag/MAG_REQ_DATA.yaml
- !include ./cmd/mag/MAG_REQ_HK.yaml
- !include ./cmd/mag/MAG_RST_COUNTERS_CC.yaml
- !include ./cmd/radio/RADIO_CONFIG_CC.yaml
- !include ./cmd/radio/RADIO_NOOP_CC.yaml
- !include ./cmd/radio/RADIO_REQ_HK.yaml
- !include ./cmd/radio/RADIO_RST_COUNTERS_CC.yaml
- !include ./cmd/reaction_wheel/RW_NOOP_CC.yaml
- !include ./cmd/reaction_wheel/RW_REQ_DATA_CC.yaml
- !include ./cmd/reaction_wheel/RW_RST_COUNTERS_CC.yaml
- !include ./cmd/reaction_wheel/RW_SET_TORQUE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_DISABLE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_ENABLE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_NOOP_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_REQ_DATA.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_REQ_HK.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_RST_COUNTERS_CC.yaml
- !include ./cmd/torquer/TORQUER_ALL_PERCENT_ON_CC.yaml
- !include ./cmd/torquer/TORQUER_DISABLE_CC.yaml
- !include ./cmd/torquer/TORQUER_ENABLE_CC.yaml
- !include ./cmd/torquer/TORQUER_NOOP_CC.yaml
- !include ./cmd/torquer/TORQUER_PERCENT_ON_CC.yaml
- !include ./cmd/torquer/TORQUER_RST_COUNTERS_CC.yaml
- !include ./cmd/torquer/TORQUER_SEND_HK_CC.yaml
