# - !Command
#   name:      TO_DEBUG_ENABLE_OUTPUT_CC
#   opcode:    0x06
#   ccsds:     { apid: 0x80 }
#   subsystem: TO
#   title:     Enable Telemetry
#   desc:      |
#     Enable Output Command
#   arguments:
#     - !Argument
#       name:  dest_ip
#       desc:  Destination IP
#       units: none
#       type:  S16
#       bytes: [0, 15]
#     - !Argument
#       name:  dest_port
#       desc:  Destination Port
#       units: none
#       type:  MSB_U16
#       bytes: [16, 17]


- !include ./cmd/adcs/ADCS_NOOP_CC.yaml
- !include ./cmd/adcs/ADCS_RST_COUNTERS_CC.yaml
- !include ./cmd/adcs/ADCS_SET_MOMENTUM_MANAGEMENT_CC.yaml
- !include ./cmd/adcs/ADCS_SET_MODE_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_DI_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_AD_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_GNC_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_AC_CC.yaml
- !include ./cmd/adcs/ADCS_SEND_DO_CC.yaml
- !include ./cmd/adcs/ADCS_REQ_HK.yaml
- !include ./cmd/adcs/ADCS_PERFORM_ADAC.yaml
- !include ./cmd/arducam/CAM_EXP3_CC.yaml
- !include ./cmd/arducam/CAM_HW_CHECK_CC.yaml
- !include ./cmd/arducam/CAM_NOOP_CC.yaml
- !include ./cmd/arducam/CAM_RESET_COUNTERS_CC.yaml
- !include ./cmd/arducam/CAM_SEND_HK_CC.yaml
- !include ./cmd/eps/EPS_NOOP_CC.yaml
- !include ./cmd/eps/EPS_REQ_HK.yaml
- !include ./cmd/eps/EPS_RST_COUNTERS_CC.yaml
- !include ./cmd/eps/EPS_SWITCH_CC.yaml
- !include ./cmd/fss/FSS_DISABLE_CC.yaml
- !include ./cmd/fss/FSS_ENABLE_CC.yaml
- !include ./cmd/fss/FSS_NOOP_CC.yaml
- !include ./cmd/fss/FSS_REQ_DATA.yaml
- !include ./cmd/fss/FSS_REQ_HK.yaml
- !include ./cmd/fss/FSS_RST_COUNTERS_CC.yaml
- !include ./cmd/imu/IMU_DISABLE_CC.yaml
- !include ./cmd/imu/IMU_ENABLE_CC.yaml
- !include ./cmd/imu/IMU_NOOP_CC.yaml
- !include ./cmd/imu/IMU_REQ_DATA.yaml
- !include ./cmd/imu/IMU_REQ_HK.yaml
- !include ./cmd/imu/IMU_RST_COUNTERS_CC.yaml
- !include ./cmd/mag/MAG_DISABLE_CC.yaml
- !include ./cmd/mag/MAG_ENABLE_CC.yaml
- !include ./cmd/mag/MAG_NOOP_CC.yaml
- !include ./cmd/mag/MAG_REQ_DATA.yaml
- !include ./cmd/mag/MAG_REQ_HK.yaml
- !include ./cmd/mag/MAG_RST_COUNTERS_CC.yaml
- !include ./cmd/radio/RADIO_CONFIG_CC.yaml
- !include ./cmd/radio/RADIO_NOOP_CC.yaml
- !include ./cmd/radio/RADIO_REQ_HK.yaml
- !include ./cmd/radio/RADIO_RST_COUNTERS_CC.yaml
- !include ./cmd/reaction_wheel/RW_NOOP_CC.yaml
- !include ./cmd/reaction_wheel/RW_REQ_DATA_CC.yaml
- !include ./cmd/reaction_wheel/RW_RST_COUNTERS_CC.yaml
- !include ./cmd/reaction_wheel/RW_SET_TORQUE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_DISABLE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_ENABLE_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_NOOP_CC.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_REQ_DATA.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_REQ_HK.yaml
- !include ./cmd/star_tracker/STAR_TRACKER_RST_COUNTERS_CC.yaml
- !include ./cmd/torquer/TORQUER_ALL_PERCENT_ON_CC.yaml
- !include ./cmd/torquer/TORQUER_DISABLE_CC.yaml
- !include ./cmd/torquer/TORQUER_ENABLE_CC.yaml
- !include ./cmd/torquer/TORQUER_NOOP_CC.yaml
- !include ./cmd/torquer/TORQUER_PERCENT_ON_CC.yaml
- !include ./cmd/torquer/TORQUER_RST_COUNTERS_CC.yaml
- !include ./cmd/torquer/TORQUER_SEND_HK_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_DISABLE_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_ENABLE_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_LOG_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_NOOP_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_REQ_DATA.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_REQ_HK.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_RST_COUNTERS_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_SERIALCONFIG_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_UNLOG_CC.yaml
- !include ./cmd/oem615/NOVATEL_OEM615_UNLOGALL_CC.yaml
- !include ./cmd/sample/SAMPLE_CONFIG_CC.yaml
- !include ./cmd/sample/SAMPLE_DISABLE_CC.yaml
- !include ./cmd/sample/SAMPLE_ENABLE_CC.yaml
- !include ./cmd/sample/SAMPLE_NOOP_CC.yaml
- !include ./cmd/sample/SAMPLE_REQ_DATA.yaml
- !include ./cmd/sample/SAMPLE_REQ_HK.yaml
- !include ./cmd/sample/SAMPLE_RST_COUNTERS_CC.yaml
- !include ./cmd/syn/SYN_ADD_DATA_CC.yaml
- !include ./cmd/syn/SYN_CONFIG_ALPHA_CC.yaml
- !include ./cmd/syn/SYN_CONFIG_DL_CC.yaml
- !include ./cmd/syn/SYN_DISP_PDATA_CC.yaml
- !include ./cmd/syn/SYN_GET_PDATA_CC.yaml
- !include ./cmd/syn/SYN_NOOP_CC.yaml
- !include ./cmd/syn/SYN_PRIO_CC.yaml
- !include ./cmd/syn/SYN_REQ_DATA.yaml
- !include ./cmd/syn/SYN_REQ_HK.yaml
- !include ./cmd/syn/SYN_RESET_CC.yaml
- !include ./cmd/syn/SYN_RST_COUNTERS_CC.yaml
- !include ./cmd/cfs/CF_DISABLE_DEQUEUE.yaml
- !include ./cmd/cfs/CF_DISABLE_DIRECTORY_POLLING.yaml
- !include ./cmd/cfs/CF_ENABLE_DEQUEUE.yaml
- !include ./cmd/cfs/CF_ENABLE_DIRECTORY_POLLING.yaml
- !include ./cmd/cfs/CF_ENADIS_AUTO_SUSPEND.yaml
- !include ./cmd/cfs/CF_FREEZE.yaml
- !include ./cmd/cfs/CF_GIVE_TAKE.yaml
- !include ./cmd/cfs/CF_KICKSTART.yaml
- !include ./cmd/cfs/CF_NOOP.yaml
- !include ./cmd/cfs/CF_PURGE_QUEUE.yaml
- !include ./cmd/cfs/CF_RESET_COUNTERS.yaml
- !include ./cmd/cfs/CF_SEND_CFG_PARAMS.yaml
- !include ./cmd/cfs/CF_SEND_HK.yaml
- !include ./cmd/cfs/CF_THAW.yaml
- !include ./cmd/cfs/CF_WRITE_QUEUE_INFO.yaml
