default:

    logging:
        name:     ait
        hostname: localhost

    cmddict:
        filename:  cmd.yaml

    tlmdict:
        filename:  tlm.yaml

    server:
        plugins: []

        inbound-streams:

            - stream:
                name: telem_stream_1
                input:
                    - "UDP"
                    - "nos_fsw"
                    - 5012
                handlers:
                    - name: gswait.handlers.CCSDSPacketHandler
                      packet_types: {'XXXXXXXXXXXX': "CCSDS_HEADER"}
