default:
    extensions:
        ait.core.cmd.Cmd: gswait.cmd.cFSCmd

    command:
        port: 3075

    logging:
        name:     ait
        hostname: localhost

    cmddict:
        filename:  cmd.yaml

    tlmdict:
        filename:  tlm.yaml

    server:

        inbound-streams:

            - stream:
                name: telem_stream_debug
                input:
                    - 5013
                handlers:
                    - name: gswait.handlers.DebugHandler

        outbound-streams:
            - stream:
                name: command_stream
                handlers:
                    - name: gswait.handlers.DebugHandler
                output:
                    - "UDP"
                    - "127.0.0.1"
                    - 5012
                command-subscriber: True
