default:

    database:
        host: influxdb
        port: 8086
        un: root
        pw: root

    extensions:
        ait.core.cmd.Cmd: gswait.cmd.cFSCmd

    command:
        port: 3075

    logging:
        name:     ait
        hostname: localhost

    cmddict:
        filename:  cmd.yaml

    tlmdict:
        filename:  tlm.yaml

    server:

        plugins:
            - plugin:
                name: ait.core.server.plugins.DataArchive
                inputs:
                    - telem_stream_debug
                datastore:
                    ait.core.db.InfluxDBBackend


        inbound-streams:

            - stream:
                name: telem_stream_debug
                input:
                    - "UDP"
                    - "0.0.0.0"
                    - 5013
                handlers:
                    - name: gswait.handlers.CCSDSPacketHandler
                      packet_types:
                        2368: "GENERIC_ADCS_HK_TLM"
                        2369: "GENERIC_ADCS_DI"
                        2370: "GENERIC_ADCS_AD"
                        2371: "GENERIC_ADCS_GNC"
                        2372: "GENERIC_ADCS_AC"
                        2373: "GENERIC_ADCS_DO"
                        2249: "ARDUCAM_EXP_TLM_T"
                        2248: "ARDUCAM_HK_TLM_T"
                        2298: "SAMPLE_HK_TLM"
                        2299: "SAMPLE_DATA_TLM"
                        2320: "GENERIC_CSS_HK_TLM"
                        2321: "GENERIC_CSS_DATA_TLM"
                        2330: "GENERIC_EPS_HK_TLM"
                        2336: "GENERIC_FSS_HK_TLM"
                        2337: "GENERIC_FSS_DATA_TLM"
                        2341: "GENERIC_IMU_HK_TLM"
                        2342: "GENERIC_IMU_DATA_TLM"
                        2346: "GENERIC_MAG_HK_TLM"
                        2347: "GENERIC_MAG_DATA_TLM"
                        2352: "GENERIC_RADIO_HK_TLM"
                        2451: "GENRW_HK_TLM_T"
                        2357: "GENERIC_STAR_TRACKER_HK_TLM"
                        2358: "GENERIC_STAR_TRACKER_DATA_TLM"
                        2362: "GENERIC_TORQUER_HK_TLM_T"
                        2160: "NOVATEL_OEM615_HK_TLM"
                        2161: "NOVATEL_OEM615_DATA_TLM"
                        2300: "SYN_HK_TLM"
                        2180: "CI_HKPACKET"
                        2224: "CF_HKPACKET"
                        2225: "CF_TRANSPACKET"
                        2212: "CS_HKPACKET"
                        2232: "DS_HKPACKET"
                        2233: "DS_FILEINFOPKT"
                        2048: "CFE_ES_HKPACKET"
                        2059: "CFE_ES_ONEAPPTLM"
                        2064: "CFE_ES_POOLSTATSTLM"
                        2063: "CFE_ES_SHELLPACKET"
                        2056: "CFE_EVS_PACKET"
                        2049: "CFE_EVS_TLMPKT"
                        2188: "FM_DIRLISTPKT"
                        2187: "FM_FILEINFOPKT"
                        2190: "FM_FREESPACEPKT"
                        2186: "FM_HOUSEKEEPINGPKT"
                        2189: "FM_OPENFILESPKT"
                        2203: "HK_HKPACKET"
                        2204: "CFE_HK_COMBINED_PKT1"
                        2221: "HS_HKPACKET"
                        2215: "LC_HKPACKET"
                        2193: "MD_DWELLPKT"
                        2192: "MD_HKTLM"
                        2183: "MM_HKPACKET"
                        2051: "CFE_SB_HKMSG"
                        2061: "CFE_SB_PREVSUBMSG"
                        2058: "CFE_SB_STATMSG"
                        2062: "CFE_SB_SUBRPRTMSG"
                        2176: "TO_HKPACKET"
                        2053: "CFE_TIME_HKPACKET"
                        2054: "CFE_TIME_DIAGPACKET"
                        2052: "CFE_TBL_HKPACKET"
                        2060: "CFE_TBL_TBLREGPACKET"
                        2200: "SCH_DIAGPACKET"
                        2199: "SCH_HKPACKET"
                        2218: "SC_HKTLM"

                      packet_secondary_header_length: 10


        outbound-streams:
            - stream:
                name: command_stream
                handlers:
                    - name: gswait.handlers.DebugHandler
                output:
                    - "UDP"
                    - "nos_fsw"
                    - 5012
                command-subscriber: True
