
- !include ccsds_header.yaml
- !include ./tlm/mag/MAG_DATA_TLM.yaml
- !include ./tlm/mag/MAG_HK_TLM.yaml
- !include ./tlm/cfdp/CFDP_ENGINE_HK.yaml
- !include ./tlm/torquer/TORQUER_HK_TLM.yaml
- !include ./tlm/radio/RADIO_HK_TLM.yaml
- !include ./tlm/css/CSS_DATA_TLM.yaml
- !include ./tlm/css/CSS_HK_TLM.yaml
- !include ./tlm/novatel_oem615/NOVATEL_OEM615_HK_TLM.yaml
- !include ./tlm/novatel_oem615/NOVATEL_OEM615_DATA_TLM.yaml
- !include ./tlm/cfs/CFS_MD_DWELLPKT.yaml
- !include ./tlm/cfs/CFS_FM_OPENFILESPKT.yaml
- !include ./tlm/cfs/CFS_CS_HKPACKET.yaml
- !include ./tlm/cfs/CFS_FM_FILEINFOPKT.yaml
- !include ./tlm/cfs/CFS_DS_FILEINFOPKT.yaml
- !include ./tlm/cfs/CFS_DS_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CF_HKPACKET.yaml
- !include ./tlm/cfs/CFS_HK_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_TBL_TBLREGPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_SB_STATMSG.yaml
- !include ./tlm/cfs/CFS_CFE_TIME_DIAGPACKET.yaml
- !include ./tlm/cfs/CFS_HS_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_EVS_TLMPKT.yaml
- !include ./tlm/cfs/CFS_CFE_EVS_PACKET.yaml
- !include ./tlm/cfs/CFS_CFE_TIME_HKPACKET.yaml
- !include ./tlm/cfs/CFS_FM_FREESPACEPKT.yaml
- !include ./tlm/cfs/CFS_CFE_ES_POOLSTATSTLM.yaml
- !include ./tlm/cfs/CFS_FM_HOUSEKEEPINGPKT.yaml
- !include ./tlm/cfs/CFS_SCH_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_ES_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CF_TRANSPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_SB_PREVSUBMSG.yaml
- !include ./tlm/cfs/CFS_CI_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_HK_COMBINED_PKT1.yaml
- !include ./tlm/cfs/CFS_CFE_ES_SHELLPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_TBL_HKPACKET.yaml
- !include ./tlm/cfs/CFS_MM_HKPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_ES_ONEAPPTLM.yaml
- !include ./tlm/cfs/CFS_SCH_DIAGPACKET.yaml
- !include ./tlm/cfs/CFS_CFE_SB_SUBRPRTMSG.yaml
- !include ./tlm/cfs/CFS_MD_HKTLM.yaml
- !include ./tlm/cfs/CFS_LC_HKPACKET.yaml
- !include ./tlm/cfs/CFS_TO_HKPACKET.yaml
- !include ./tlm/cfs/CFS_FM_DIRLISTPKT.yaml
- !include ./tlm/cfs/CFS_CFE_SB_HKMSG.yaml
- !include ./tlm/cfs/CFS_SC_HKTLM.yaml
- !include ./tlm/star_tracker/STAR_TRACKER_DATA_TLM.yaml
- !include ./tlm/star_tracker/STAR_TRACKER_HK_TLM.yaml
- !include ./tlm/imu/IMU_HK_TLM.yaml
- !include ./tlm/imu/IMU_DATA_TLM.yaml
- !include ./tlm/syn/SYN_HK_TLM.yaml
- !include ./tlm/adcs/ADCS_DO.yaml
- !include ./tlm/adcs/ADCS_HK_TLM.yaml
- !include ./tlm/adcs/ADCS_AD.yaml
- !include ./tlm/adcs/ADCS_AC.yaml
- !include ./tlm/adcs/ADCS_DI.yaml
- !include ./tlm/adcs/ADCS_GNC.yaml
- !include ./tlm/arducam/ARDUCAM_EXP_TLM.yaml
- !include ./tlm/arducam/ARDUCAM_HK_TLM.yaml
- !include ./tlm/sample/SAMPLE_DATA_TLM.yaml
- !include ./tlm/sample/SAMPLE_HK_TLM.yaml
- !include ./tlm/eps/EPS_HK_TLM.yaml
- !include ./tlm/fss/FSS_HK_TLM.yaml
- !include ./tlm/fss/FSS_DATA_TLM.yaml
- !include ./tlm/reaction_wheel/REACTION_WHEEL_HK_TLM.yaml
