
- !include ccsds_header.yaml
- !include ./tlm/adcs/GENERIC_ADCS_AC.yaml
- !include ./tlm/adcs/GENERIC_ADCS_AD.yaml
- !include ./tlm/adcs/GENERIC_ADCS_DI.yaml
- !include ./tlm/adcs/GENERIC_ADCS_DO.yaml
- !include ./tlm/adcs/GENERIC_ADCS_GNC.yaml
- !include ./tlm/adcs/GENERIC_ADCS_HK_TLM.yaml
- !include ./tlm/mag/GENERIC_MAG_DATA_TLM.yaml
- !include ./tlm/mag/GENERIC_MAG_HK_TLM.yaml
- !include ./tlm/torquer/GENERIC_TORQUER_HK_TLM_T.yaml
- !include ./tlm/radio/GENERIC_RADIO_HK_TLM.yaml
- !include ./tlm/css/GENERIC_CSS_DATA_TLM.yaml
- !include ./tlm/css/GENERIC_CSS_HK_TLM.yaml
- !include ./tlm/novatel_oem615/NOVATEL_OEM615_HK_TLM.yaml
- !include ./tlm/novatel_oem615/NOVATEL_OEM615_DATA_TLM.yaml
- !include ./tlm/star_tracker/GENERIC_STAR_TRACKER_DATA_TLM.yaml
- !include ./tlm/star_tracker/GENERIC_STAR_TRACKER_HK_TLM.yaml
- !include ./tlm/imu/GENERIC_IMU_HK_TLM.yaml
- !include ./tlm/imu/GENERIC_IMU_DATA_TLM.yaml
- !include ./tlm/syn/SYN_HK_TLM.yaml
- !include ./tlm/arducam/ARDUCAM_EXP_TLM_T.yaml
- !include ./tlm/arducam/ARDUCAM_HK_TLM_T.yaml
- !include ./tlm/sample/SAMPLE_DATA_TLM.yaml
- !include ./tlm/sample/SAMPLE_HK_TLM.yaml
- !include ./tlm/eps/GENERIC_EPS_HK_TLM.yaml
- !include ./tlm/fss/GENERIC_FSS_HK_TLM.yaml
- !include ./tlm/fss/GENERIC_FSS_DATA_TLM.yaml
- !include ./tlm/reaction_wheel/GENRW_HK_TLM_T.yaml
