!Packet
name: CSS_DATA_TLM
fields:
- !Field
  name: RAW_CSS_0
  desc: Raw css[0] (0-65535)
  type: LSB_U16

- !Field
  name: RAW_CSS_1
  desc: Raw css[1] (0-65535)
  type: LSB_U16

- !Field
  name: RAW_CSS_2
  desc: Raw css[2] (0-65535)
  type: LSB_U16

- !Field
  name: RAW_CSS_3
  desc: Raw css[3] (0-65535)
  type: LSB_U16

- !Field
  name: RAW_CSS_4
  desc: Raw css[4] (0-65535)
  type: LSB_U16

- !Field
  name: RAW_CSS_5
  desc: Raw css[5] (0-65535)
  type: LSB_U16
