!Packet
name: STAR_TRACKER_DATA_TLM
fields:
- !Field
  name: STAR_TRACKER_Q0
  desc: generic_star_tracker data q0 component
  type: LSB_D64

- !Field
  name: STAR_TRACKER_Q1
  desc: generic_star_tracker data q1 component
  type: LSB_D64

- !Field
  name: STAR_TRACKER_Q2
  desc: generic_star_tracker data q2 component
  type: LSB_D64

- !Field
  name: STAR_TRACKER_Q3
  desc: generic_star_tracker data q3 component
  type: LSB_D64

- !Field
  name: STAR_TRACKER_IS_VALID
  desc: generic_star_tracker data is valid flag
  type: U8
