name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - run: poetry install
      name: Poetry Install
    - run: poetry run pytest
      name: Poetry Test